### ISSUE TITLE
strange bytes after jpeg end marker

### ISSUE THREAD

**Issue by jsheffer** [psanford/node-mjpeg-test-server#1]
After opening http://mjpeg.sanford.io/ with Mozilla (28.0) and switched on
SmartSniff, there were captured strange bytes after end marker FF D9:

00 00 3F FF D9 0D 0A 0D  0A 36 62 35 0D 0A 2D 2D         ..?˙Ł... .6b5..-- 
6D 79 62 6F 75 6E 64 61  72 79 0D 0A 43 6F 6E 74            mybounda ry..Cont 
65 6E 74 2D 54 79 70 65   3A 20 69 6D 61 67 65 2F            ent-Type : im

After FF D9 and before "--myboundary" there should be only
0D-s and 0A-s, but there are also 36 62 35. Such kind of different
bytes can be found at the end of EVERY jpeg fragment, but investigating
source code of server, cannot find, who writes these bytes.
Started to explore this after building small mjpeg server, which
worked on Mozilla, but not on Android. 
Thanks for every explanation.

**Comment by psanford** [comment]
I just ran into this for another project. By default node will set the Transfer-Encoding to 'chunked' if you don't set a content-length for the http response. Chunked encoding writes the length of each chunk in hex and then the chunk itself. That is what you are seeing here.

I can't find anything that says combining chunked encoding with multipart is forbidden. It seems like the major browsers support it. I'm not sure how common it is with devices that emit mjpeg (e.g. webcams). You can disable chunked encoding in node by setting the Transfer-Encoding to something besides 'chunked', like empty string.

**Comment by jsheffer** [comment]
Hello,
thank you for reply.
It is correct that specifying the content
length improves transfer. As time has passed,
my code is better now and working quite stable.
Actually this is an OEM IP-camera, based on
microcontroller, not on PC. So I cannot use
javascript, but C and must receive and send every
byte on my own. For illustration, here are some
lines from working sample:

```
 const char github_header[219] = {
 "HTTP/1.1 200 OK\r\n"
 "Server: mjpeg_server\r\n"
 "Cache-Control: no-cache, no-store, must-revalidate, pre-check=0, 
```

post-check=0, max-age=0\r\n"
     "Pragma: no-cache\r\n"
     "Content-Type: 
multipart/x-mixed-replace;boundary=boundarydonotcross \r\n\r\n"};

for every jpeg-frame I am sending:

```
         sprintf(s,  "--boundarydonotcross \r\n"            // send0 
```

is the length of
                             "Content-Type: image/jpeg\r\n" // jpeg 
frame body,
                             "Content-Length: %d\r\n"        // 621 
bytes is jpeg header + eoi
                             "\r\n",            send0+621);
             net_send_block(s, mystrlen(s));

```
         net_send_block(CCM, send0+621);     // jpeg content itself
         net_send_block("\r\n", 2);                    // CR+LF for 
```

the end

Best regards,
Jüri Sheffer.
